// =========================================================================
// cache_def.svh — Cache & Memory geometry constants
//
// AUTO-GENERATED by tools/vivado_core/cache_header_gen.py
// Do NOT edit manually — changes will be overwritten.
// Edit vivado_config.yaml -> memory section instead, then run:
//   python -m tools.vivado_cli --gen-config
// =========================================================================

`ifndef CACHE_DEF_SVH
`define CACHE_DEF_SVH

// --- SRAM (Main Memory) ---
`define SRAM_DATA_WIDTH  32
`define SRAM_DEPTH       8192
`define SRAM_ADDR_WIDTH  13
`define SRAM_WEA_WIDTH   4

// --- DDR3 Main Memory (via MIG) ---
`define DDR3_ENABLED        1
`define DDR3_IP_NAME        "mig_axi_32"
`define DDR3_MEM_SIZE       134217728
`define DDR3_AXI_ADDR_WIDTH 27
`define DDR3_AXI_DATA_WIDTH 32
`define DDR3_AXI_ID_WIDTH   8
`define DDR3_DATA_RATE      800
`define DDR3_BASE_ADDR      32'h8000_0000

`define CLK_WIZ_IP_NAME     "clk_wiz_0"
`define CLK_WIZ_PRIM_IN_FREQ  100
`define CLK_WIZ_DDR_REF_FREQ 100
`define MIG_UI_CLK_FREQ     100

// --- I-Cache ---
`define ICACHE_NUM_SETS    8
`define ICACHE_NUM_WAYS    4
`define ICACHE_TAG_WIDTH   7
`define ICACHE_LINE_WORDS  8
`define ICACHE_LINE_WIDTH  256
`define ICACHE_DEPTH       32
`define ICACHE_ADDR_WIDTH  5
`define ICACHE_WEA_WIDTH   32

// Address bit slices for ICACHE
`define ICACHE_WORD_OFF_LO 2
`define ICACHE_WORD_OFF_HI 4
`define ICACHE_SET_IDX_LO 5
`define ICACHE_SET_IDX_HI 7
`define ICACHE_TAG_LO     8
`define ICACHE_TAG_HI     14
`define ICACHE_TAG_ENTRY_WIDTH 8
`define ICACHE_SET_IDX_WIDTH 3
`define ICACHE_WAY_WIDTH    2
`define ICACHE_TAG_BRAM_WIDTH      32
`define ICACHE_TAG_BRAM_DEPTH      8
`define ICACHE_TAG_BRAM_ADDR_WIDTH 3
`define ICACHE_TAG_BRAM_WEA_WIDTH  4
`define ICACHE_TAG_BRAM_BYTE_SIZE  8

// --- D-Cache ---
`define DCACHE_NUM_SETS    8
`define DCACHE_NUM_WAYS    4
`define DCACHE_TAG_WIDTH   7
`define DCACHE_LINE_WORDS  8
`define DCACHE_LINE_WIDTH  256
`define DCACHE_DEPTH       32
`define DCACHE_ADDR_WIDTH  5
`define DCACHE_WEA_WIDTH   32

// Address bit slices for DCACHE
`define DCACHE_WORD_OFF_LO 2
`define DCACHE_WORD_OFF_HI 4
`define DCACHE_SET_IDX_LO 5
`define DCACHE_SET_IDX_HI 7
`define DCACHE_TAG_LO     8
`define DCACHE_TAG_HI     14
`define DCACHE_TAG_ENTRY_WIDTH 9
`define DCACHE_SET_IDX_WIDTH 3
`define DCACHE_WAY_WIDTH    2
`define DCACHE_TAG_BRAM_WIDTH      36
`define DCACHE_TAG_BRAM_DEPTH      8
`define DCACHE_TAG_BRAM_ADDR_WIDTH 3
`define DCACHE_TAG_BRAM_WEA_WIDTH  4
`define DCACHE_TAG_BRAM_BYTE_SIZE  9

// --- Tag storage mode ---
`define USE_TAG_BRAM 1

// --- TLB geometry ---
`define TLB_NUM_WAYS           4
`define TLB_NUM_SETS          4
`define TLB_SET_IDX_WIDTH     2
`define TLB_WAY_WIDTH         2

`define TLB_FLAG_ENTRY_WIDTH  32
`define TLB_FLAG_BRAM_WIDTH   128
`define TLB_FLAG_BRAM_DEPTH   4
`define TLB_FLAG_BRAM_ADDR_WIDTH 2
`define TLB_FLAG_BRAM_WEA_WIDTH  16
`define TLB_FLAG_BRAM_BYTE_SIZE  8

`define TLB_DATA_ENTRY_WIDTH  32
`define TLB_DATA_BRAM_WIDTH   128
`define TLB_DATA_BRAM_DEPTH   4
`define TLB_DATA_BRAM_ADDR_WIDTH 2
`define TLB_DATA_BRAM_WEA_WIDTH  16
`define TLB_DATA_BRAM_BYTE_SIZE  8

// --- TLB storage mode ---
`define USE_TLB_BRAM 1

`endif // CACHE_DEF_SVH
