// =========================================================================
// cache_def.svh — Cache & Memory geometry constants
//
// AUTO-GENERATED by tools/vivado_core/cache_header_gen.py
// Do NOT edit manually — changes will be overwritten.
// Edit vivado_config.yaml -> memory section instead, then run:
//   python -m tools.vivado_cli --gen-config
// =========================================================================

`ifndef CACHE_DEF_SVH
`define CACHE_DEF_SVH

// --- SRAM (Main Memory) ---
`define SRAM_DATA_WIDTH  32
`define SRAM_DEPTH       8192
`define SRAM_ADDR_WIDTH  13

// --- I-Cache ---
`define ICACHE_NUM_SETS    8
`define ICACHE_NUM_WAYS    4
`define ICACHE_TAG_WIDTH   7
`define ICACHE_LINE_WORDS  8
`define ICACHE_LINE_WIDTH  256
`define ICACHE_DEPTH       32
`define ICACHE_ADDR_WIDTH  5
`define ICACHE_WEA_WIDTH   32

// Address bit slices for ICACHE
`define ICACHE_WORD_OFF_LO 2
`define ICACHE_WORD_OFF_HI 4
`define ICACHE_SET_IDX_LO 5
`define ICACHE_SET_IDX_HI 7
`define ICACHE_TAG_LO     8
`define ICACHE_TAG_HI     14
`define ICACHE_TAG_ENTRY_WIDTH 8
`define ICACHE_SET_IDX_WIDTH 3
`define ICACHE_WAY_WIDTH    2

// --- D-Cache ---
`define DCACHE_NUM_SETS    8
`define DCACHE_NUM_WAYS    4
`define DCACHE_TAG_WIDTH   7
`define DCACHE_LINE_WORDS  8
`define DCACHE_LINE_WIDTH  256
`define DCACHE_DEPTH       32
`define DCACHE_ADDR_WIDTH  5
`define DCACHE_WEA_WIDTH   32

// Address bit slices for DCACHE
`define DCACHE_WORD_OFF_LO 2
`define DCACHE_WORD_OFF_HI 4
`define DCACHE_SET_IDX_LO 5
`define DCACHE_SET_IDX_HI 7
`define DCACHE_TAG_LO     8
`define DCACHE_TAG_HI     14
`define DCACHE_TAG_ENTRY_WIDTH 9
`define DCACHE_SET_IDX_WIDTH 3
`define DCACHE_WAY_WIDTH    2

// --- Tag storage mode ---
`define USE_TAG_BRAM 0

`endif // CACHE_DEF_SVH
