vivado: vivado
project: simplecpu_soc
part: xc7a200tfbg676-2

timeouts:
  project: 1800
  simulation: 72000
  bitstream: 7200
  program: 120

ddr3:
  enabled: true
  name: mig_axi_32
  version: "4.2"
  project_file: docs/Reference/mig/mig_a.prj

clock:
  name: clk_wiz_0
  version: "6.0"
  input_mhz: 100.0
  feedback_multiplier: 10.0
  input_divider: 1
  outputs_mhz: [40.0, 100.0, 200.0]
  reset_type: ACTIVE_LOW
