# FPGA约束文件 - System Top (CPU + Bus4LZU)

# 时钟信号连接 (100MHz)
set_property PACKAGE_PIN AC19 [get_ports clk]
create_clock -period 10.000 [get_ports clk]

# 复位信号，低电平有效
set_property PACKAGE_PIN Y3 [get_ports resetn]

# 单步调试按键，低电平有效
# set_property PACKAGE_PIN Y5 [get_ports btn_clk]

# 拨码开关 SW0-SW7
set_property PACKAGE_PIN AC21 [get_ports {sw[0]}]
set_property PACKAGE_PIN AD24 [get_ports {sw[1]}]
set_property PACKAGE_PIN AC22 [get_ports {sw[2]}]
set_property PACKAGE_PIN AC23 [get_ports {sw[3]}]
set_property PACKAGE_PIN AB6  [get_ports {sw[4]}]
set_property PACKAGE_PIN W6   [get_ports {sw[5]}]
set_property PACKAGE_PIN AA7  [get_ports {sw[6]}]
set_property PACKAGE_PIN Y6   [get_ports {sw[7]}]

# IO标准设置
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports resetn]
set_property IOSTANDARD LVCMOS33 [get_ports btn_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]

# 触摸屏引脚连接
set_property PACKAGE_PIN J25 [get_ports lcd_rst]
set_property PACKAGE_PIN H18 [get_ports lcd_cs]
set_property PACKAGE_PIN K16 [get_ports lcd_rs]
set_property PACKAGE_PIN L8  [get_ports lcd_wr]
set_property PACKAGE_PIN K8  [get_ports lcd_rd]
set_property PACKAGE_PIN J15 [get_ports lcd_bl_ctr]
set_property PACKAGE_PIN H9  [get_ports {lcd_data_io[0]}]
set_property PACKAGE_PIN K17 [get_ports {lcd_data_io[1]}]
set_property PACKAGE_PIN J20 [get_ports {lcd_data_io[2]}]
set_property PACKAGE_PIN M17 [get_ports {lcd_data_io[3]}]
set_property PACKAGE_PIN L17 [get_ports {lcd_data_io[4]}]
set_property PACKAGE_PIN L18 [get_ports {lcd_data_io[5]}]
set_property PACKAGE_PIN L15 [get_ports {lcd_data_io[6]}]
set_property PACKAGE_PIN M15 [get_ports {lcd_data_io[7]}]
set_property PACKAGE_PIN M16 [get_ports {lcd_data_io[8]}]
set_property PACKAGE_PIN L14 [get_ports {lcd_data_io[9]}]
set_property PACKAGE_PIN M14 [get_ports {lcd_data_io[10]}]
set_property PACKAGE_PIN F22 [get_ports {lcd_data_io[11]}]
set_property PACKAGE_PIN G22 [get_ports {lcd_data_io[12]}]
set_property PACKAGE_PIN G21 [get_ports {lcd_data_io[13]}]
set_property PACKAGE_PIN H24 [get_ports {lcd_data_io[14]}]
set_property PACKAGE_PIN J16 [get_ports {lcd_data_io[15]}]
set_property PACKAGE_PIN L19 [get_ports ct_int]
set_property PACKAGE_PIN J24 [get_ports ct_sda]
set_property PACKAGE_PIN H21 [get_ports ct_scl]
set_property PACKAGE_PIN G24 [get_ports ct_rstn]

# 触摸屏IO标准设置
set_property IOSTANDARD LVCMOS33 [get_ports lcd_rst]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_cs]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_rs]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_wr]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_rd]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_bl_ctr]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data_io[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports ct_int]
set_property IOSTANDARD LVCMOS33 [get_ports ct_sda]
set_property IOSTANDARD LVCMOS33 [get_ports ct_scl]
set_property IOSTANDARD LVCMOS33 [get_ports ct_rstn]

# UART引脚连接
set_property PACKAGE_PIN F23 [get_ports uart_rx]
set_property PACKAGE_PIN H19 [get_ports uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]

# SPI引脚连接 (SPI Flash)
set_property PACKAGE_PIN N18 [get_ports spi_miso]
set_property PACKAGE_PIN P19 [get_ports spi_mosi]
set_property PACKAGE_PIN R20 [get_ports spi_ss]
set_property PACKAGE_PIN P20 [get_ports spi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports spi_miso]
set_property IOSTANDARD LVCMOS33 [get_ports spi_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports spi_ss]
set_property IOSTANDARD LVCMOS33 [get_ports spi_clk]

# GPIO引脚连接 (扩展IO EXT0_IO[15:0])
set_property PACKAGE_PIN AD26 [get_ports {gpio_io[0]}]
set_property PACKAGE_PIN T19  [get_ports {gpio_io[1]}]
set_property PACKAGE_PIN T20  [get_ports {gpio_io[2]}]
set_property PACKAGE_PIN AD25 [get_ports {gpio_io[3]}]
set_property PACKAGE_PIN AE25 [get_ports {gpio_io[4]}]
set_property PACKAGE_PIN AF25 [get_ports {gpio_io[5]}]
set_property PACKAGE_PIN U22  [get_ports {gpio_io[6]}]
set_property PACKAGE_PIN AF24 [get_ports {gpio_io[7]}]
set_property PACKAGE_PIN U21  [get_ports {gpio_io[8]}]
set_property PACKAGE_PIN V24  [get_ports {gpio_io[9]}]
set_property PACKAGE_PIN V23  [get_ports {gpio_io[10]}]
set_property PACKAGE_PIN W23  [get_ports {gpio_io[11]}]
set_property PACKAGE_PIN AE23 [get_ports {gpio_io[12]}]
set_property PACKAGE_PIN V22  [get_ports {gpio_io[13]}]
set_property PACKAGE_PIN U25  [get_ports {gpio_io[14]}]
set_property PACKAGE_PIN U26  [get_ports {gpio_io[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io[15]}]
