// =========================================================================
// cache_def.svh — Cache & Memory geometry constants
//
// AUTO-GENERATED by tools/vivado_core/cache_header_gen.py
// Do NOT edit manually — changes will be overwritten.
// Edit vivado_config.yaml -> memory section instead, then run:
//   python -m tools.vivado_cli --gen-config
// =========================================================================

`ifndef CACHE_DEF_SVH
`define CACHE_DEF_SVH

// --- ROM (Boot ROM) ---
`define ROM_DATA_WIDTH  32
`define ROM_DEPTH       8192
`define ROM_ADDR_WIDTH  13
`define ROM_WEA_WIDTH   4

// --- DDR3 Main Memory (via MIG) ---
`define DDR3_ENABLED        1
`define DDR3_IP_NAME        "mig_axi_32"
`define DDR3_MEM_SIZE       134217728
`define DDR3_AXI_ADDR_WIDTH 27
`define DDR3_AXI_DATA_WIDTH 32
`define DDR3_AXI_ID_WIDTH   8
`define DDR3_DATA_RATE      800
`define DDR3_BASE_ADDR      32'h8000_0000

`define CLK_WIZ_IP_NAME     "clk_wiz_0"
`define CLK_WIZ_PRIM_IN_FREQ  100
`define CLK_WIZ_DDR_REF_FREQ 100
`define MIG_UI_CLK_FREQ     100

// --- I-Cache ---
`define ICACHE_NUM_SETS    8
`define ICACHE_NUM_WAYS    2
`define ICACHE_TAG_WIDTH   19
`define ICACHE_LINE_WORDS  8
`define ICACHE_LINE_WIDTH  256
`define ICACHE_DEPTH       16
`define ICACHE_ADDR_WIDTH  4
`define ICACHE_WEA_WIDTH   32

// Address bit slices for ICACHE
`define ICACHE_WORD_OFF_LO 2
`define ICACHE_WORD_OFF_HI 4
`define ICACHE_SET_IDX_LO 5
`define ICACHE_SET_IDX_HI 7
`define ICACHE_TAG_LO     8
`define ICACHE_TAG_HI     26
`define ICACHE_TAG_ENTRY_WIDTH 20
`define ICACHE_SET_IDX_WIDTH 3
`define ICACHE_WAY_WIDTH    1

// --- D-Cache ---
`define DCACHE_NUM_SETS    8
`define DCACHE_NUM_WAYS    2
`define DCACHE_TAG_WIDTH   19
`define DCACHE_LINE_WORDS  8
`define DCACHE_LINE_WIDTH  256
`define DCACHE_DEPTH       16
`define DCACHE_ADDR_WIDTH  4
`define DCACHE_WEA_WIDTH   32

// Address bit slices for DCACHE
`define DCACHE_WORD_OFF_LO 2
`define DCACHE_WORD_OFF_HI 4
`define DCACHE_SET_IDX_LO 5
`define DCACHE_SET_IDX_HI 7
`define DCACHE_TAG_LO     8
`define DCACHE_TAG_HI     26
`define DCACHE_TAG_ENTRY_WIDTH 21
`define DCACHE_SET_IDX_WIDTH 3
`define DCACHE_WAY_WIDTH    1

// --- Tag storage mode ---
`define USE_TAG_BRAM 0

// --- TLB geometry ---
`define TLB_NUM_WAYS           2
`define TLB_NUM_SETS          8
`define TLB_SET_IDX_WIDTH     3
`define TLB_WAY_WIDTH         1

`define TLB_FLAG_ENTRY_WIDTH  32
`define TLB_FLAG_BRAM_WIDTH   64
`define TLB_FLAG_BRAM_DEPTH   8
`define TLB_FLAG_BRAM_ADDR_WIDTH 3
`define TLB_FLAG_BRAM_WEA_WIDTH  8
`define TLB_FLAG_BRAM_BYTE_SIZE  8

`define TLB_DATA_ENTRY_WIDTH  32
`define TLB_DATA_BRAM_WIDTH   64
`define TLB_DATA_BRAM_DEPTH   8
`define TLB_DATA_BRAM_ADDR_WIDTH 3
`define TLB_DATA_BRAM_WEA_WIDTH  8
`define TLB_DATA_BRAM_BYTE_SIZE  8

`endif // CACHE_DEF_SVH
